// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in entgo.io/bug/ent/runtime.go

const (
	Version = "v0.10.2-0.20220421072242-7d153c7683d8"           // Version of ent codegen.
	Sum     = "h1:sLL9fq7cv2mLseskWOO0L2dKXNxH4DO5QwXrFRN7FLw=" // Sum of ent codegen.
)
